### ISSUE TITLE
Inviting you to vote on some Armbian stuff

### ISSUE THREAD

**Issue by lanefu** [ThomasKaiser/Knowledge#1]
Hey TK sorry didn't know of a smarter way to reach out to you.

In the private forum i have proposals for def of supported and mission statement up for a vote.    To clarify, my intentions of the proposals is to make the scope of some decisions small enough that we could break out of the cycle of circular discussions and inch forward with some more structure.

I know you're pretty tired of the project at this point, but you're a huge part of Armbians success so I wanted to make sure you had an opportunity to participate and be heard.

**Comment by ThomasKaiser** [comment]
Haha, you want more babbling about Igor's private pet project where in the end he always simply does whatever strikes his head without giving a shit about any 'consensus' or concerns of other developers?

Good luck with this and also the try to get an idea about what 'supported' means instead of questioning why Igor wants to turn a community forum into a support forum.

And I really can't believe what's going on there, e.g. https://forum.armbian.com/topic/10027-debian-vs-ubuntu/ -- the first and only question would be whether the guy tests the two images on two different SD cards (a 'Desktop Linux' relies on fast local storage). In another thread insane BS is spread about specific hardware capabilities of a board (maybe just to promote a youtube channel?). Why bother...

**Comment by ThomasKaiser** [comment]
Haha, [With another words - several hundreds or thousands of euros has to be thrown at the website this year](https://forum.armbian.com/topic/10033-search-option-for-download-page/?do=findComment&comment=76032) -- that's what you get if you try to establish a 'brand' for no reason while still trying to keep the project itself a pet project where the 'owner' decides whatever he wants without communicating 'too much'. So sick of it after wasting days of my life for silly babbling about 'project goals' and how to improve on 'distro stability' instead of the constant upgrade nightmares and so on...

**Comment by ThomasKaiser** [comment]
@lanefu enabling hfsplus will make Armbian famous as the pet project [enabling data loss at scale](https://en.wikipedia.org/wiki/HFS_Plus#Linux). Good luck!

**Comment by lanefu** [comment]
oh shit!  thanks for the warning. yeah wont be enabling that by default

**Comment by ghost** [comment]
Hello Thomas, I know this is not the right place to contact you, but is there a way to
```temp_limit=64```
on armbian as well? I've been googling for over an hour. All I could figure out myself is lowering clock on my Odroid HC1, but I'd prefer to keep default settings and instead throttle by temperature readings.

Please forgive for necroing this bug. Didn't want to write on Heise, send to a random email or annoy you :)

**Comment by ThomasKaiser** [comment]
> but is there a way to `temp_limit=64` on armbian as well?

If you're talking about the RPi's `config.txt` setting then no, this will neither work in Armbian nor with Linux in general since this is nothing that's related to Linux anyway (it's the proprietary ThreadX stuff controlling the RPi hardware --> [details](https://ownyourbits.com/2019/02/02/whats-wrong-with-the-raspberry-pi/)).

In case you want to set 64°C as a throttling threshold then it depends on the kernel you're using on normal ARM devices and how to define this stuff there. With ODROID HC1 and running most probably kernel 4.14 you would need to edit the device tree settings (use package `device-tree-compiler`) but usually this can also be adjusted through `sysfs` nodes. I would do a web search for 'thermal treshold sysfs xu4' or ask in ODROID forum.

**Comment by ghost** [comment]
Thanks for the fast reply and pointing me in the right directions. I will research this more now and not bump the thread further. Have a great weekend!
