### ISSUE TITLE
zstd was not measured multi-threaded in M1 article

### ISSUE THREAD

**Issue by hmage** [ThomasKaiser/Knowledge#4]
In the [Exploring Apple Silicon](https://github.com/ThomasKaiser/Knowledge/blob/master/articles/Exploring_Apple_Silicon_on_MacBookAir10.md#energy-aware-computing) article, maybe author was not aware of `-T` switch in zstd, and therefore called it a `single-threaded tool`.

From manpage:
```
       o   -T#, --threads=#: Compress using # working threads (default: 1). If
           # is 0, attempt to detect and use the number of physical CPU cores.
           In  all  cases,  the  nb  of  threads  is  capped to ZSTDMT_NBWORK-
           ERS_MAX==200. This modifier does nothing if zstd is compiled  with-
           out multithread support.
```

It's very unlikely that zstd was compiled without multithread support.

**Comment by ThomasKaiser** [comment]
Yep, you're right. Wasn't aware of `-T`. I adjusted the wording accordingly and will update the article soon. Unfortunately not able to retest in a reasonable way since our testing machines (the Air as well as the 13" M1 MacBook Pro) have been handed over to colleagues (normal users with a totally different point of view and focus on testing but already reluctant to switch back to Intel AKA 'fan noise').

Thanks for the hint. As soon as there's a 16" M1 thingy available we'll order and retest this time also with various `zstd -T` invocations.
